require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'BrekekePhone' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'

 pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

 pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

 post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
    config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
   end
  end
 end
end
