const CustomImages = {
  CallAcceptedLogo: require('assets/accepted-call.png'),
  CallDeclinedLogo: require('assets/decline-call.png'),
  CountryFlagLogo: require('assets/country.png'),
  QooqieLogo: require('assets/qooqie-logo.png'),
  Keys: require('assets/CallActionBtnImages/keys.png'),
  MicrophoneOff: require('assets/CallActionBtnImages/unmute.png'),
  Microphone: require('assets/CallActionBtnImages/microphone.png'),
  Park: require('assets/CallActionBtnImages/park.png'),
  Unhold: require('assets/CallActionBtnImages/unhold.png'),
  Pause: require('assets/CallActionBtnImages/pause.png'),
  RecordWhite: require('assets/CallActionBtnImages/record-circle-white.png'),
  Record: require('assets/CallActionBtnImages/record.png'),
  Transfer: require('assets/CallActionBtnImages/transfer.png'),
  VideoOff: require('assets/CallActionBtnImages/video-off.png'),
  Video: require('assets/CallActionBtnImages/video-white.png'),
  VolumeHigh: require('assets/CallActionBtnImages/volume-high.png'),
  VolumeMedium: require('assets/CallActionBtnImages/volume-medium.png'),
  Brand: require('assets/brand.png'),
  Logo: require('assets/logo.png'),
  HeaderBackButton: require('assets/headerBack.png'),
  BackgroundBlue: require('assets/background_blue.png'),
  signInBanner: require('assets/login/banner.png'),
}

export default CustomImages
